# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet/IP Interface
version: "0.0.2"
slug: bacnetinterface
description: Bepacom BACnet/IP interface
url: "https://github.com/GravySeal/bepacom-repo/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 7813
panel_icon: mdi:router-wireless-settings
map:
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
ports:
  7813/tcp: 7813
  7813/udp: 7813
  47808/tcp: 47808
  47808/udp: 47808
  47809/tcp: 47809
  47809/udp: 47809
options:
  objectname: BigBoss
  address: host
  objectIdentifier: 420
  webServ: 127.0.0.1
  maxApduLenghtAccepted: 1024
  segmentationSupported: segmentedBoth
  vendorID: 15
  foreignBBMD: 128.253.109.254
  foreignTTL: 30
  maxSegmentsAccepted: 16
schema:
  objectname: str
  address: str
  objectIdentifier: int
  webServ: str
  maxApduLenghtAccepted: int?
  segmentationSupported: str?
  vendorID: int?
  foreignBBMD: str?
  foreignTTL: int?
  maxSegmentsAccepted: int?