# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet/IP Interface
version: "0.0.1"
slug: bacnetinterface
description: Bepacom BACnet/IP interface
url: "https://github.com/GravySeal/bepacom-repo/tree/main/BACnet/BACnet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true			#enable webui
host_network: true		#voor gebruik van de Host adapter/netwerkverbinding
panel_icon: mdi:router-wireless-settings
map:
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  objectname: BigBoss
  objectIdentifier: 420
  maxApduLenghtAccepted: 1024
  segmentationSupported: segmentedBoth
  vendorID: 15
  foreignBBMD: 128.253.109.254
  foreignTTL: 30
  maxSegmentsAccepted: 16
schema:
  objectname: str
  objectIdentifier: int
  maxApduLenghtAccepted: int?
  segmentationSupported: str?
  vendorID: int?
  foreignBBMD: str?
  foreignTTL: int?
  maxSegmentsAccepted: int?