---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:11.0.4
  armhf: ghcr.io/hassio-addons/base-python:11.0.4
  armv7: ghcr.io/hassio-addons/base-python:11.0.4
  amd64: ghcr.io/hassio-addons/base-python:11.0.4
  i386: ghcr.io/hassio-addons/base-python:11.0.4
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bepacom BACnet/IP interface"
  org.opencontainers.image.description: "Bepacom add-on for Home Assistant. It can act as a virtual BACnet device and read data."
  org.opencontainers.image.source: "https://github.com/Bepacom-Raalte/bepacom-HA-Addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
