# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bepacom BACnet/IP Interface Development Version
version: "1.5.0b11"
slug: bacnetinterface_dev
description: Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API
url: "https://github.com/Bepacom-Raalte/bepacom-HA-Addons/tree/main/bacnetinterface"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_entry: webapp
host_network: true
hassio_api: true
homeassistant_api: true
panel_icon: mdi:router-wireless-settings
map:
  - config:rw
ports:
  80/tcp: null
  47808/udp: 47808
ports_description:
  80/tcp: Default webserver port
  47808/udp: BACnet port
options:
  objectName: EcoPanel
  address: auto
  objectIdentifier: 420
  defaultPriority: 15
  devices_setup:
    - deviceID: all
      CoV_lifetime: 600
      CoV_list:
        - all
      quick_poll_rate: 5
      quick_poll_list: []
      slow_poll_rate: 600
      slow_poll_list:
        - all
      resub_on_iam: true
      reread_on_iam: false
  entity_list: []
  api_accessible: false
  loglevel: WARNING
  segmentation: segmentedBoth
schema:
  objectName: str
  address: str
  objectIdentifier: int
  defaultPriority: int(1,16)
  loglevel: list(DEBUG|INFO|WARNING|ERROR|CRITICAL|)
  devices_setup:
    - deviceID: str? 
      CoV_lifetime: int(60,28800)?
      CoV_list:
        - str? 
      quick_poll_rate: int(3,30)?
      quick_poll_list:
        - str? 
      slow_poll_rate: int(30,3000)?
      slow_poll_list:
        - str?
      resub_on_iam: bool? #idk
      reread_on_iam: bool? #idk
  entity_list:
    - str?
  api_accessible: bool?
  foreignBBMD: str?
  foreignTTL: str?
  vendorID: int?
  maxApduLenghtAccepted: int?
  segmentation: list(segmentedBoth|segmentedTransmit|segmentedReceive|noSegmentation||)?
  maxSegmentsAccepted: int?

