# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bepacom BACnet/IP Interface Development Version
version: "1.3.0"
slug: bacnetinterface_dev
description: Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.
url: "https://github.com/Bepacom-Raalte/bepacom-HA-Addons/tree/main/bacnetinterface"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
# Mind to use webapp instead of webapp/... This causes ingress to misbehave.
ingress_entry: webapp
host_network: true
hassio_api: true
homeassistant_api: true
panel_icon: mdi:router-wireless-settings
map:
  - config:rw
ports:
  80/tcp: 80
  47808/udp: 47808
ports_description:
  80/tcp: Default webserver port
  47808/udp: BACnet port
options:
  objectName: EcoPanel
  address: auto
  objectIdentifier: 420
  defaultPriority: 15
  updateInterval: 60
  subscriptions:
    analogInput: true
    analogOutput: true
    analogValue: true
    binaryInput: true
    binaryOutput: true
    binaryValue: true
    multiStateInput: true
    multiStateOutput: true
    multiStateValue: true
  entity_list: []
  loglevel: WARNING
  segmentation: segmentedBoth
schema:
  objectName: str
  address: str
  objectIdentifier: int
  defaultPriority: "int(1,16)"
  loglevel: list(DEBUG|INFO|WARNING|ERROR|CRITICAL|)
  updateInterval: int
  subscriptions:
    analogInput: bool
    analogOutput: bool
    analogValue: bool
    binaryInput: bool
    binaryOutput: bool
    binaryValue: bool
    multiStateInput: bool
    multiStateOutput: bool
    multiStateValue: bool
  entity_list:
    - str?
  foreignBBMD: str?
  foreignTTL: str?
  vendorID: int?
  maxApduLenghtAccepted: int?
  segmentation: list(segmentedBoth|segmentedTransmit|segmentedReceive|noSegmentation||)?
  maxSegmentsAccepted: int?
