# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet interface
version: "0.0.1"
slug: BACnetInterface
description: Bepacom BACnet interface for detecting BACnet devices on the network.
url: "https://github.com/GravySeal/bepacom-repo/tree/main/BACnet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Op je BACus"
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
