# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet/IP Interface
version: "0.0.1"
slug: bacnetinterface
description: BACnet/IP interface. It'll discover BACnet devices on your network. On the WebUI you'll be able to set up the devices to be used as Home Assistant Entities.
url: "https://github.com/GravySeal/bepacom-repo/tree/main/BACnet/BACnet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
