# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet/IP Interface
version: "0.0.1"
slug: bacnetinterface
description: Bepacom BACnet/IP interface.
url: "https://github.com/GravySeal/bepacom-repo/tree/main/BACnet/BACnet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
