# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Zeroconf Test
version: "0.0.1"
slug: zeroconf
description: Zeroconf
url: "https://github.com/GravySeal/bepacom-repo/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: false
panel_icon: mdi:router-wireless-settings
map:
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
discovery:
  - detailed_hello_world_push
ports:
  5353/tcp: 5353
  5353/udp: 5353