---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:13.1.0
  armhf: ghcr.io/hassio-addons/base-python:13.1.0
  armv7: ghcr.io/hassio-addons/base-python:13.1.0
  amd64: ghcr.io/hassio-addons/base-python:13.1.0
  i386: ghcr.io/hassio-addons/base-python:13.1.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bepacom BACnet/IP interface"
  org.opencontainers.image.description: "Bepacom BACnet/IP add-on for Home Assistant."
  org.opencontainers.image.source: "https://github.com/Bepacom-Raalte/bepacom-HA-Addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
