---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:14.0.1
  armhf: ghcr.io/hassio-addons/base-python:14.0.1
  armv7: ghcr.io/hassio-addons/base-python:14.0.1
  amd64: ghcr.io/hassio-addons/base-python:14.0.1
  i386: ghcr.io/hassio-addons/base-python:14.0.1
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bepacom BACnet/IP interface"
  org.opencontainers.image.description: "Bepacom BACnet/IP add-on for Home Assistant."
  org.opencontainers.image.source: "https://github.com/NemiahUK/bepacom-HA-Addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
