# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: BACnet/IP interface
version: "0.0.1"
slug: bacnetinterface
description: Bepacom BACnet interface. It finds the BACnet devices on your network and neatly displays them as entities after setting up in our lovely WebUI!
url: "https://github.com/GravySeal/bepacom-repo/tree/main/bacnetinterface"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world...?"
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
