# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bepacom EcoPanel BACnet/IP Interface
version: "0.1.1"
slug: bacnetinterface
description: Bepacom BACnet/IP interface for the Bepacom EcoPanel.
url: "https://github.com/GravySeal/bepacom-repo/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_entry: webapp/
host_network: true
panel_icon: mdi:router-wireless-settings
startup: services
map:
  - config:rw
ports:
  80/tcp: 80
  47808/udp: 47808
ports_description:
  80/tcp: Default webserver port
  47808/udp: BACnet port
options:
  objectName: EcoPanel
  address: auto
  objectIdentifier: 420
schema:
  objectName: str
  address: str
  objectIdentifier: int
  loglevel: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
  maxApduLenghtAccepted: int?
  segmentationSupported: str?
  vendorID: int?
  foreignBBMD: str?
  foreignTTL: int?
  maxSegmentsAccepted: int?
