# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Bepacom EcoPanel BACnet/IP Interface
version: "0.0.5"
slug: bacnetinterface
description: Bepacom BACnet/IP interface for the Bepacom EcoPanel
url: "https://github.com/GravySeal/bepacom-repo/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_entry: webapp/
host_network: true
full_access: false
panel_icon: mdi:router-wireless-settings
map:
  - backup:rw
  - config:rw
  - media:rw
  - share:rw
  - ssl:rw
ports:
  80/tcp: 80
  7813/tcp: 7813
  7813/udp: 7813
  47808/udp: 47808
options:
  objectname: EcoPanel
  address: 0.0.0.0
  objectIdentifier: 420
  maxApduLenghtAccepted: 1024
  segmentationSupported: segmentedBoth
  vendorID: 15
  maxSegmentsAccepted: 16
schema:
  objectname: str
  address: str
  objectIdentifier: int
  maxApduLenghtAccepted: int?
  segmentationSupported: str?
  vendorID: int?
  foreignBBMD: str?
  foreignTTL: int?
  maxSegmentsAccepted: int?
