# generated by datamodel-codegen:
#   filename:  json.json
#   timestamp: 2023-02-03T08:30:59+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
