---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  armhf: ghcr.io/home-assistant/armhf-base-python:3.11-alpine3.18
  armv7: ghcr.io/home-assistant/armv7-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
  i386: ghcr.io/home-assistant/i386-base-python:3.11-alpine3.18
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Bepacom BACnet/IP interface"
  org.opencontainers.image.description: "Bepacom add-on for Home Assistant. It can act as a virtual BACnet device and read data."
  org.opencontainers.image.source: "https://github.com/NemiahUK/bepacom-HA-Addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"